---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: /data/k8s/local/hostpath
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-hostpath-pod
  labels:
    name: myapp
spec:
  nodeSelector:
    kubernetes.io/hostname: __HOSTNAME_REPLACE__
  volumes:
    - name: pvc-hostpath
      persistentVolumeClaim:
        claimName: pvc-hostpath
  initContainers:
  - name: volume-permissions
    image: busybox
    command: ["sh", "-c", "chown -R 101:101 /usr/share/nginx/html"]
    volumeMounts:
    - name: pvc-hostpath
      mountPath: /usr/share/nginx/html
  containers:
  - name: nginx
    image: nginx:1.27.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: pvc-hostpath
